# Generated by Django 2.1.1 on 2018-12-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income_visualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='収入', max_length=100)),
                ('income', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='visualization',
            name='day',
            field=models.DateField(blank=True, null=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='visualization',
            name='name',
            field=models.CharField(choices=[('消費', '消費'), ('浪費', '浪費'), ('投資', '投資')], default=0, max_length=100),
        ),
    ]
